spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/our_worldcup
    username: root
    password: root
  sql.init.mode: always
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        database-platform: org.hibernate.dialect.MySQL8Dialect
        generate-ddl: true
        show_sql: true
        defer-datasource-initialization: true
        format_sql: true
        # hinernate가 생성되는 sql 쿼리에 주석을 추가함.
        use_sql_comments: true
login:
  scheme: http
  port: 8080
  default-host: 'localhost'
  default-failure-path: '/login'
  default-success-path: '/'