spring:
  config:
    activate:
      on-profile: aws
cloud:
  aws:
    s3:
      bucket: our-worldcup-s3-bucket
#      dev-bucket: our-worldcup-s3-bucket-dev
    region:
      static: us-east-2
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
