spring:
  profiles:
    include: dev
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${CLIENT_ID_KAKAO}
            client-secret: ${CLIENT_SECRET_KAKAO}
            client-authentication-method: client_secret_post
            scope: [profile_nickname, account_email, profile_image]
            redirect-uri: ${REDIRECT_URI_KAKAO} # 
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    hiddenmethod:
      filter:
        enabled: true
jwt:
  secret-key: ${JWT_SECRET_KEY}
  token-validity-in-sec: 1800 # 30분
  refresh-token-validity-in-sec: 86400 # 3일

management:
  endpoints:
    web:
      exposure:
        include: health

cloud:
  aws:
    s3:
      bucket: our-worldcup-s3-bucket
    #      dev-bucket: our-worldcup-s3-bucket-dev
    region:
      static: us-east-2
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY_ID}
      secret-key: ${AWS_S3_SECRET_ACCESS_KEY}
springdoc:
  api-docs:
    path: /api-docs # api-docs url: localhost:8080/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html # swagger url: localhost:8080/swagger-ui/index.html
    tags-sorter: alpha # alpha: 알파벳 순 태그 정렬
    operations-sorter: method # , method: HTTP METHOD 순 정렬
  use-fqn: true # Fully Qualified Name -> 클래스의 완전한 이름(패키지 이름 포함)
  cache:
    disabled: true