spring:
  profiles:
    include: [aws, dev]
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${CLIENT_ID_KAKAO}
            client-secret: ${CLIENT_SECRET_KAKAO}
            client-authentication-method: client_secret_post
            scope: [profile_nickname, account_email, profile_image]
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    hiddenmethod:
      filter:
        enabled: true
jwt:
  secret-key: ${jwt-secret-key}
  token-validity-in-sec: 1800 # 30분
  refresh-token-validity-in-sec: 86400 # 3일

management:
  endpoints:
    web:
      exposure:
        include: health



---
#spring:
#  profiles:
#    include:
#      - aws
#    active: local
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 20MB
#      max-request-size: 30MB
#  datasource:
#    hikari:
#      maximum-pool-size: 25
# TODO: 이후 비동기 처리 때 추가
#  task:
#    execution:
#      pool:
#        # CORE 스레드 수
#        core-size: 8
#        # 스레드 최대 개수
#        max-size: 8


#logging:
#  level:
#    root: debug