cloud:
  aws:
    s3:
      bucket: ourworldcup-s3-bucket
      dev-bucket: ourworldcup-s3-bucket-dev
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
